version: '3.1'
services:
  jsight-spring-boot:
    build: 
      context: ./../
      dockerfile: ./docker/Dockerfile
    container_name: jsight_spring_boot
    ports:
      - 8080:8080
    volumes:
      - ./..:/app
      - ./../jsight-lib/libjsight/1.0.0:/usr/local/lib
      - ./../jsight-lib/libjsightjava/1.0.0:/usr/java/packages/lib
    working_dir: /app
    command: mvn spring-boot:run
